"
Constants for the mixpanel support
"
Class {
	#name : #MixpanelConstants,
	#superclass : #Object,
	#category : #'Willow-Mixpanel'
}

{ #category : #Accessing }
MixpanelConstants class >> alias [

	^ 'alias'
]

{ #category : #Accessing }
MixpanelConstants class >> identify [

	^ 'identify'
]

{ #category : #Accessing }
MixpanelConstants class >> mixpanel [
	
	^ 'mixpanel'
]

{ #category : #Accessing }
MixpanelConstants class >> register [

	^ 'register'
]

{ #category : #Accessing }
MixpanelConstants class >> registerOnce [

	^ 'register_once'
]

{ #category : #Accessing }
MixpanelConstants class >> timeEvent [

	^ 'time_event'
]

{ #category : #Accessing }
MixpanelConstants class >> track [

	^ 'track'
]

{ #category : #Accessing }
MixpanelConstants class >> trackForms [

	^ 'track_forms'
]

{ #category : #Accessing }
MixpanelConstants class >> trackLinks [

	^ 'track_links'
]
